fix optional chaining
swift-script/swift-script pull request #10
Opened 2017-03-12 00:30 UTC by koher

- Supported function calls `foo?(bar)` and subscripts `foo?[bar]`.

2017-03-12 02:16 UTC, rintaro requested changes
We need to update `_exprPostfixUnary`.
As of now, it only accepts postfix `!`

2017-03-13 17:26 UTC, koher commented
@rintaro Currently `foo?.bar` is parsed as a binary operation: `foo` + `?.` + `bar`. `foo?(bar)` is `foo` + `?` + `(bar)` and `foo?[bar]` is `foo` + `?` + `[bar]` as well. Could you fix the parser for binary operations?

2017-03-14 02:45 UTC, rintaro commented
I added a commit to parse postfix '?' as a `PostfixUnaryOperation`.

2017-03-14 04:02 UTC, koher commented
@rintaro Thanks! LGTM😃

2017-03-14 04:35 UTC, rintaro approved these changes

2017-03-14 04:36 UTC, merged